export const REQUEST_ORDER_COUNT = 'REQUEST_ORDER_COUNT';

export const RECEIVE_ORDER_COUNT = 'RECEIVE_ORDER_COUNT';

export const SET_UNREAD_COUNT = 'SET_UNREAD_COUNT';

export const SET_USER_INFO = 'SET_USER_INFO';

export const NAVIGATOR_TITLE = 'NAVIGATOR_TITLE';

export const MAIN_TAB_SELECT = 'MAIN_TAB_SELECT';

export const REQUEST_COUPON_LIST = 'REQUEST_COUPON_LIST';

export const RECEIVE_COUPON_LIST = 'RECEIVE_COUPON_LIST';
