export const REQUEST_ORDER_COUNT = 'REQUEST_ORDER_COUNT';

export const RECEIVE_ORDER_COUNT = 'RECEIVE_ORDER_COUNT';

export const SET_UNREAD_COUNT = 'SET_UNREAD_COUNT';

export const SET_USER_INFO = 'SET_USER_INFO';